//
//  MALGenres.swift
//  Animebox
//

import Foundation

/// MAL v2 no tiene un endpoint de lista de géneros/temas (a diferencia de
/// Jikan). Listas estáticas extraídas directamente de los formularios de
/// búsqueda reales de myanimelist.net/anime.php y manga.php (fuente de
/// verdad priorizada para usuarios con sesión iniciada) — no del endpoint de
/// géneros de Jikan. Anime y manga tienen espacios de IDs parcialmente
/// distintos (p. ej. "Suspense" = 41 en anime pero 45 en manga, "Crossdressing"
/// = 81 en anime pero 44 en manga, y manga tiene el tema exclusivo "Memoir"),
/// así que se mantienen listas separadas en vez de una única lista compartida.
nonisolated enum MALGenres {
    static let animeGenres: [NamedEntity] = [
        NamedEntity(malId: 1, type: "anime", name: "Action", url: nil),
        NamedEntity(malId: 2, type: "anime", name: "Adventure", url: nil),
        NamedEntity(malId: 5, type: "anime", name: "Avant Garde", url: nil),
        NamedEntity(malId: 46, type: "anime", name: "Award Winning", url: nil),
        NamedEntity(malId: 28, type: "anime", name: "Boys Love", url: nil),
        NamedEntity(malId: 4, type: "anime", name: "Comedy", url: nil),
        NamedEntity(malId: 8, type: "anime", name: "Drama", url: nil),
        NamedEntity(malId: 10, type: "anime", name: "Fantasy", url: nil),
        NamedEntity(malId: 26, type: "anime", name: "Girls Love", url: nil),
        NamedEntity(malId: 47, type: "anime", name: "Gourmet", url: nil),
        NamedEntity(malId: 14, type: "anime", name: "Horror", url: nil),
        NamedEntity(malId: 7, type: "anime", name: "Mystery", url: nil),
        NamedEntity(malId: 22, type: "anime", name: "Romance", url: nil),
        NamedEntity(malId: 24, type: "anime", name: "Sci-Fi", url: nil),
        NamedEntity(malId: 36, type: "anime", name: "Slice of Life", url: nil),
        NamedEntity(malId: 30, type: "anime", name: "Sports", url: nil),
        NamedEntity(malId: 37, type: "anime", name: "Supernatural", url: nil),
        NamedEntity(malId: 41, type: "anime", name: "Suspense", url: nil)
    ]

    static let animeThemes: [NamedEntity] = [
        NamedEntity(malId: 50, type: "anime", name: "Adult Cast", url: nil),
        NamedEntity(malId: 51, type: "anime", name: "Anthropomorphic", url: nil),
        NamedEntity(malId: 52, type: "anime", name: "CGDCT", url: nil),
        NamedEntity(malId: 53, type: "anime", name: "Childcare", url: nil),
        NamedEntity(malId: 54, type: "anime", name: "Combat Sports", url: nil),
        NamedEntity(malId: 81, type: "anime", name: "Crossdressing", url: nil),
        NamedEntity(malId: 55, type: "anime", name: "Delinquents", url: nil),
        NamedEntity(malId: 39, type: "anime", name: "Detective", url: nil),
        NamedEntity(malId: 56, type: "anime", name: "Educational", url: nil),
        NamedEntity(malId: 57, type: "anime", name: "Gag Humor", url: nil),
        NamedEntity(malId: 58, type: "anime", name: "Gore", url: nil),
        NamedEntity(malId: 35, type: "anime", name: "Harem", url: nil),
        NamedEntity(malId: 59, type: "anime", name: "High Stakes Game", url: nil),
        NamedEntity(malId: 13, type: "anime", name: "Historical", url: nil),
        NamedEntity(malId: 60, type: "anime", name: "Idols (Female)", url: nil),
        NamedEntity(malId: 61, type: "anime", name: "Idols (Male)", url: nil),
        NamedEntity(malId: 62, type: "anime", name: "Isekai", url: nil),
        NamedEntity(malId: 63, type: "anime", name: "Iyashikei", url: nil),
        NamedEntity(malId: 64, type: "anime", name: "Love Polygon", url: nil),
        NamedEntity(malId: 74, type: "anime", name: "Love Status Quo", url: nil),
        NamedEntity(malId: 65, type: "anime", name: "Magical Sex Shift", url: nil),
        NamedEntity(malId: 66, type: "anime", name: "Mahou Shoujo", url: nil),
        NamedEntity(malId: 17, type: "anime", name: "Martial Arts", url: nil),
        NamedEntity(malId: 18, type: "anime", name: "Mecha", url: nil),
        NamedEntity(malId: 67, type: "anime", name: "Medical", url: nil),
        NamedEntity(malId: 38, type: "anime", name: "Military", url: nil),
        NamedEntity(malId: 19, type: "anime", name: "Music", url: nil),
        NamedEntity(malId: 6, type: "anime", name: "Mythology", url: nil),
        NamedEntity(malId: 68, type: "anime", name: "Organized Crime", url: nil),
        NamedEntity(malId: 69, type: "anime", name: "Otaku Culture", url: nil),
        NamedEntity(malId: 20, type: "anime", name: "Parody", url: nil),
        NamedEntity(malId: 70, type: "anime", name: "Performing Arts", url: nil),
        NamedEntity(malId: 71, type: "anime", name: "Pets", url: nil),
        NamedEntity(malId: 40, type: "anime", name: "Psychological", url: nil),
        NamedEntity(malId: 3, type: "anime", name: "Racing", url: nil),
        NamedEntity(malId: 72, type: "anime", name: "Reincarnation", url: nil),
        NamedEntity(malId: 73, type: "anime", name: "Reverse Harem", url: nil),
        NamedEntity(malId: 21, type: "anime", name: "Samurai", url: nil),
        NamedEntity(malId: 23, type: "anime", name: "School", url: nil),
        NamedEntity(malId: 75, type: "anime", name: "Showbiz", url: nil),
        NamedEntity(malId: 29, type: "anime", name: "Space", url: nil),
        NamedEntity(malId: 11, type: "anime", name: "Strategy Game", url: nil),
        NamedEntity(malId: 31, type: "anime", name: "Super Power", url: nil),
        NamedEntity(malId: 76, type: "anime", name: "Survival", url: nil),
        NamedEntity(malId: 77, type: "anime", name: "Team Sports", url: nil),
        NamedEntity(malId: 78, type: "anime", name: "Time Travel", url: nil),
        NamedEntity(malId: 82, type: "anime", name: "Urban Fantasy", url: nil),
        NamedEntity(malId: 32, type: "anime", name: "Vampire", url: nil),
        NamedEntity(malId: 79, type: "anime", name: "Video Game", url: nil),
        NamedEntity(malId: 83, type: "anime", name: "Villainess", url: nil),
        NamedEntity(malId: 80, type: "anime", name: "Visual Arts", url: nil),
        NamedEntity(malId: 48, type: "anime", name: "Workplace", url: nil)
    ]

    static let mangaGenres: [NamedEntity] = [
        NamedEntity(malId: 1, type: "manga", name: "Action", url: nil),
        NamedEntity(malId: 2, type: "manga", name: "Adventure", url: nil),
        NamedEntity(malId: 5, type: "manga", name: "Avant Garde", url: nil),
        NamedEntity(malId: 46, type: "manga", name: "Award Winning", url: nil),
        NamedEntity(malId: 28, type: "manga", name: "Boys Love", url: nil),
        NamedEntity(malId: 4, type: "manga", name: "Comedy", url: nil),
        NamedEntity(malId: 8, type: "manga", name: "Drama", url: nil),
        NamedEntity(malId: 10, type: "manga", name: "Fantasy", url: nil),
        NamedEntity(malId: 26, type: "manga", name: "Girls Love", url: nil),
        NamedEntity(malId: 47, type: "manga", name: "Gourmet", url: nil),
        NamedEntity(malId: 14, type: "manga", name: "Horror", url: nil),
        NamedEntity(malId: 7, type: "manga", name: "Mystery", url: nil),
        NamedEntity(malId: 22, type: "manga", name: "Romance", url: nil),
        NamedEntity(malId: 24, type: "manga", name: "Sci-Fi", url: nil),
        NamedEntity(malId: 36, type: "manga", name: "Slice of Life", url: nil),
        NamedEntity(malId: 30, type: "manga", name: "Sports", url: nil),
        NamedEntity(malId: 37, type: "manga", name: "Supernatural", url: nil),
        NamedEntity(malId: 45, type: "manga", name: "Suspense", url: nil)
    ]

    static let mangaThemes: [NamedEntity] = [
        NamedEntity(malId: 50, type: "manga", name: "Adult Cast", url: nil),
        NamedEntity(malId: 51, type: "manga", name: "Anthropomorphic", url: nil),
        NamedEntity(malId: 52, type: "manga", name: "CGDCT", url: nil),
        NamedEntity(malId: 53, type: "manga", name: "Childcare", url: nil),
        NamedEntity(malId: 54, type: "manga", name: "Combat Sports", url: nil),
        NamedEntity(malId: 44, type: "manga", name: "Crossdressing", url: nil),
        NamedEntity(malId: 55, type: "manga", name: "Delinquents", url: nil),
        NamedEntity(malId: 39, type: "manga", name: "Detective", url: nil),
        NamedEntity(malId: 56, type: "manga", name: "Educational", url: nil),
        NamedEntity(malId: 57, type: "manga", name: "Gag Humor", url: nil),
        NamedEntity(malId: 58, type: "manga", name: "Gore", url: nil),
        NamedEntity(malId: 35, type: "manga", name: "Harem", url: nil),
        NamedEntity(malId: 59, type: "manga", name: "High Stakes Game", url: nil),
        NamedEntity(malId: 13, type: "manga", name: "Historical", url: nil),
        NamedEntity(malId: 60, type: "manga", name: "Idols (Female)", url: nil),
        NamedEntity(malId: 61, type: "manga", name: "Idols (Male)", url: nil),
        NamedEntity(malId: 62, type: "manga", name: "Isekai", url: nil),
        NamedEntity(malId: 63, type: "manga", name: "Iyashikei", url: nil),
        NamedEntity(malId: 64, type: "manga", name: "Love Polygon", url: nil),
        NamedEntity(malId: 75, type: "manga", name: "Love Status Quo", url: nil),
        NamedEntity(malId: 65, type: "manga", name: "Magical Sex Shift", url: nil),
        NamedEntity(malId: 66, type: "manga", name: "Mahou Shoujo", url: nil),
        NamedEntity(malId: 17, type: "manga", name: "Martial Arts", url: nil),
        NamedEntity(malId: 18, type: "manga", name: "Mecha", url: nil),
        NamedEntity(malId: 67, type: "manga", name: "Medical", url: nil),
        NamedEntity(malId: 68, type: "manga", name: "Memoir", url: nil),
        NamedEntity(malId: 38, type: "manga", name: "Military", url: nil),
        NamedEntity(malId: 19, type: "manga", name: "Music", url: nil),
        NamedEntity(malId: 6, type: "manga", name: "Mythology", url: nil),
        NamedEntity(malId: 69, type: "manga", name: "Organized Crime", url: nil),
        NamedEntity(malId: 70, type: "manga", name: "Otaku Culture", url: nil),
        NamedEntity(malId: 20, type: "manga", name: "Parody", url: nil),
        NamedEntity(malId: 71, type: "manga", name: "Performing Arts", url: nil),
        NamedEntity(malId: 72, type: "manga", name: "Pets", url: nil),
        NamedEntity(malId: 40, type: "manga", name: "Psychological", url: nil),
        NamedEntity(malId: 3, type: "manga", name: "Racing", url: nil),
        NamedEntity(malId: 73, type: "manga", name: "Reincarnation", url: nil),
        NamedEntity(malId: 74, type: "manga", name: "Reverse Harem", url: nil),
        NamedEntity(malId: 21, type: "manga", name: "Samurai", url: nil),
        NamedEntity(malId: 23, type: "manga", name: "School", url: nil),
        NamedEntity(malId: 76, type: "manga", name: "Showbiz", url: nil),
        NamedEntity(malId: 29, type: "manga", name: "Space", url: nil),
        NamedEntity(malId: 11, type: "manga", name: "Strategy Game", url: nil),
        NamedEntity(malId: 31, type: "manga", name: "Super Power", url: nil),
        NamedEntity(malId: 77, type: "manga", name: "Survival", url: nil),
        NamedEntity(malId: 78, type: "manga", name: "Team Sports", url: nil),
        NamedEntity(malId: 79, type: "manga", name: "Time Travel", url: nil),
        NamedEntity(malId: 83, type: "manga", name: "Urban Fantasy", url: nil),
        NamedEntity(malId: 32, type: "manga", name: "Vampire", url: nil),
        NamedEntity(malId: 80, type: "manga", name: "Video Game", url: nil),
        NamedEntity(malId: 81, type: "manga", name: "Villainess", url: nil),
        NamedEntity(malId: 82, type: "manga", name: "Visual Arts", url: nil),
        NamedEntity(malId: 48, type: "manga", name: "Workplace", url: nil)
    ]
}
